// <auto-generated />
using DesignAid.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesignAid.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DesignAidDbContext))]
    [Migration("20260215120325_AddSettingsTable")]
    partial class AddSettingsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("DesignAid.Domain.Entities.Asset", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.AssetComponent", b =>
                {
                    b.Property<string>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("AssetId", "PartId");

                    b.HasIndex("AssetId");

                    b.HasIndex("PartId");

                    b.ToTable("AssetComponents", (string)null);
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.AssetSubAsset", b =>
                {
                    b.Property<string>("ParentAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("ParentAssetId", "ChildAssetId");

                    b.HasIndex("ChildAssetId");

                    b.HasIndex("ParentAssetId");

                    b.ToTable("AssetSubAssets", (string)null);
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.DesignComponent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactHashes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ArtifactHashesJson");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MetaDataJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartTypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("StandardIdsJson");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("Parts", (string)null);

                    b.HasDiscriminator<string>("PartTypeDiscriminator").HasValue("DesignComponent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.DesignStandard", b =>
                {
                    b.Property<string>("StandardId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationRuleJson")
                        .HasColumnType("TEXT");

                    b.HasKey("StandardId");

                    b.ToTable("Standards", (string)null);
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.HandoverRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommittedHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignComponentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DesignComponentId");

                    b.HasIndex("PartId");

                    b.HasIndex("Status");

                    b.ToTable("HandoverHistory", (string)null);
                });

            modelBuilder.Entity("DesignAid.Infrastructure.Persistence.SettingsEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("DesignAid.Infrastructure.VectorSearch.VectorIndexEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dimensions")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("VectorIndex", (string)null);
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.FabricatedPart", b =>
                {
                    b.HasBaseType("DesignAid.Domain.Entities.DesignComponent");

                    b.Property<string>("DrawingPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceTreatment")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Fabricated");
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.PurchasedPart", b =>
                {
                    b.HasBaseType("DesignAid.Domain.Entities.DesignComponent");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecificationPath")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.ToTable("Parts", t =>
                        {
                            t.Property("LeadTimeDays")
                                .HasColumnName("PurchasedPart_LeadTimeDays");
                        });

                    b.HasDiscriminator().HasValue("Purchased");
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.StandardPart", b =>
                {
                    b.HasBaseType("DesignAid.Domain.Entities.DesignComponent");

                    b.Property<string>("Finish")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialGrade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardNumber")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Standard");
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.AssetComponent", b =>
                {
                    b.HasOne("DesignAid.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetComponents")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignAid.Domain.Entities.DesignComponent", "Part")
                        .WithMany("AssetComponents")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.AssetSubAsset", b =>
                {
                    b.HasOne("DesignAid.Domain.Entities.Asset", "ChildAsset")
                        .WithMany("ParentAssets")
                        .HasForeignKey("ChildAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DesignAid.Domain.Entities.Asset", "ParentAsset")
                        .WithMany("ChildAssets")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildAsset");

                    b.Navigation("ParentAsset");
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.HandoverRecord", b =>
                {
                    b.HasOne("DesignAid.Domain.Entities.DesignComponent", null)
                        .WithMany("HandoverRecords")
                        .HasForeignKey("DesignComponentId");

                    b.HasOne("DesignAid.Domain.Entities.DesignComponent", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetComponents");

                    b.Navigation("ChildAssets");

                    b.Navigation("ParentAssets");
                });

            modelBuilder.Entity("DesignAid.Domain.Entities.DesignComponent", b =>
                {
                    b.Navigation("AssetComponents");

                    b.Navigation("HandoverRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
